// Client -> Server
export const C = {
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  SET_MODE: 'SET_MODE',
  SET_MAP: 'SET_MAP',
  START_GAME: 'START_GAME',
  INPUT: 'INPUT',
  LEAVE: 'LEAVE',
};

// Server -> Client
export const S = {
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_JOINED: 'ROOM_JOINED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  HOST_CHANGED: 'HOST_CHANGED',
  MODE_CHANGED: 'MODE_CHANGED',
  MAP_CHANGED: 'MAP_CHANGED',
  GAME_STARTED: 'GAME_STARTED',
  SNAPSHOT: 'SNAPSHOT',
  TAG_EVENT: 'TAG_EVENT',
  FREEZE_EVENT: 'FREEZE_EVENT',
  UNFREEZE_EVENT: 'UNFREEZE_EVENT',
  GAME_OVER: 'GAME_OVER',
  RETURN_TO_LOBBY: 'RETURN_TO_LOBBY',
  ERROR: 'ERROR',
};

export const MODES = {
  CLASSIC: 'classic',
  FREEZE: 'freeze',
  INFECTION: 'infection',
};
